(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const db=window.ACTIVITIES_V2||[];
const KEYS={state:'mns_v2_state',profiles:'mns_v2_profiles',fav:'mns_v2_fav',history:'mns_v2_history',ratings:'mns_v2_ratings',inventory:'mns_v2_inventory',week:'mns_v2_week'};
const defaults={activeChild:'c1',childEnergy:'normal',parentEnergy:'normal',motion:true,sound:false,filters:{location:'home',time:20,categories:[],solo:false,noPrep:false,noMess:false,onlyNew:false,atHome:false,siblings:false}};
const defaultProfiles=[{id:'c1',name:'Dieťa',age:4,avatar:'🦊',interests:['animals','creative'],notes:''}];
const inventoryItems=[['paper','📄 Papier'],['crayons','🖍 Pastelky'],['blocks','🧱 Kocky'],['socks','🧦 Ponožky'],['pillows','🛋 Vankúše'],['kitchen','🥣 Kuchynské veci'],['tape','🧻 Páska'],['ball','⚽ Lopta'],['cups','🥤 Kelímky'],['playdough','🟣 Plastelína'],['paint','🎨 Farby'],['boxes','📦 Krabice'],['clips','📎 Štipce'],['music','🎵 Hudba'],['none','🙌 Nič špeciálne']];
const interests=[['animals','🐾 Zvieratá'],['colors','🌈 Farby'],['space','🚀 Vesmír'],['nature','🌿 Príroda'],['creative','🎨 Tvorenie'],['movement','🤸 Pohyb'],['pretend','🎭 Fantázia'],['brain','🧠 Hádanky']];
let state=load(KEYS.state,defaults), profiles=load(KEYS.profiles,defaultProfiles), fav=load(KEYS.fav,[]), history=load(KEYS.history,[]), ratings=load(KEYS.ratings,{}), inventory=load(KEYS.inventory,['paper','crayons','blocks','socks','pillows','kitchen','none']);
let current=null, deferredPrompt=null, lastShake=0;
function clone(o){return JSON.parse(JSON.stringify(o))}function load(k,d){try{const v=JSON.parse(localStorage.getItem(k));return v??clone(d)}catch{return clone(d)}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function profile(){return profiles.find(p=>p.id===state.activeChild)||profiles[0]}
function ageText(a){return a===2?'2 roky':a===3||a===4?`${a} roky`:`${a} rokov`}
function categoryLabel(c){return ({movement:'Pohyb',creative:'Tvorenie',brain:'Premýšľanie',pretend:'Fantázia',calm:'Pokoj',sensory:'Objavovanie'})[c]||'Hra'}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2200)}
function beep(){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=620;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>{o.stop();c.close()},70)}catch{}}
function saveAll(){save(KEYS.state,state);save(KEYS.profiles,profiles);save(KEYS.fav,fav);save(KEYS.history,history);save(KEYS.ratings,ratings);save(KEYS.inventory,inventory)}
function showView(name){$$('.view').forEach(v=>{v.hidden=true;v.classList.remove('active')});const v=$(`#${name}View`);if(v){v.hidden=false;v.classList.add('active');window.scrollTo({top:0,behavior:state.motion?'smooth':'auto'})}$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='discover')renderResults();if(name==='saved')renderSaved();if(name==='progress')renderProgress();if(name==='profile')renderProfile();if(name==='kid')renderKidChoices()}
function rankActivities(opts={}){const p=profile(), playedIds=new Set(history.map(h=>h.id));let list=db.filter(a=>p.age>=a.ageMin&&p.age<=a.ageMax);const f=opts.filters||state.filters;if(f.location)list=list.filter(a=>a.locations.includes(f.location));if(f.time)list=list.filter(a=>a.time<=Number(f.time)+5);if(f.categories?.length)list=list.filter(a=>f.categories.includes(a.category));if(f.solo)list=list.filter(a=>a.solo);if(f.noPrep)list=list.filter(a=>a.prep<=1);if(f.noMess)list=list.filter(a=>a.mess===0);if(f.onlyNew)list=list.filter(a=>!playedIds.has(a.id));if(f.siblings)list=list.filter(a=>a.siblings);if(f.atHome)list=list.filter(a=>a.noPrep||a.tools.every(t=>inventory.includes(t)));
 const pe=opts.parentEnergy||state.parentEnergy, ce=opts.childEnergy||state.childEnergy;
 return list.map(a=>{let s=0;if(a.childEnergy===ce)s+=5;if(pe==='zero'){if(a.parentEnergy==='low')s+=7;if(a.solo)s+=5;if(a.prep===0)s+=4;if(a.mess===0)s+=3}else if(pe==='high'){if(a.parentEnergy==='high'||a.parentEnergy==='medium')s+=4}else if(a.parentEnergy==='medium'||a.parentEnergy==='low')s+=3;if(p.interests?.some(i=>a.tags.includes(i)))s+=4;const r=ratings[a.id];if(r==='love')s+=8;if(r==='no')s-=10;const rec=history.findIndex(h=>h.id===a.id);if(rec===-1)s+=5;else s-=Math.max(0,7-rec/4);if(a.tools.length&&a.tools.every(t=>inventory.includes(t)))s+=2;return {a,s:s+Math.random()*1.8}}).sort((x,y)=>y.s-x.s).map(x=>x.a)}
function pick(opts={}){const list=rankActivities(opts);return list[0]||db.filter(a=>profile().age===a.ageMin)[Math.floor(Math.random()*100)]}
function showActivity(a){if(!a)return;current=a;const played=history.find(h=>h.id===a.id);$('#activityEmoji').textContent=a.emoji;$('#activityTitle').textContent=a.title;$('#activityKicker').textContent=categoryLabel(a.category).toUpperCase();$('#activityIntro').textContent=a.intro;$('#activityMeta').innerHTML=[`👶 ${ageText(a.ageMin)}`,`⏱ ${a.time} min`,`🧑 príprava ${a.prep} min`,a.solo?'🧸 môže samo':'🤝 spolu',played?'🕘 už hrané':'✨ nové'].map(x=>`<span>${x}</span>`).join('');$('#activitySteps').innerHTML=a.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('#activityMaterials').textContent=a.materials;$('#easierText').textContent=a.easier;$('#harderText').textContent=a.harder;$('#activityWhy').textContent=a.why;$('#activitySafety').textContent=a.safety;$('#meterPrep').textContent=meter(a.prep===0?1:a.prep===1?2:3);$('#meterMess').textContent=meter(a.mess+1);$('#meterSupervision').textContent=meter(a.supervision);$('#meterSolo').textContent=meter(a.soloScore);$('#heartBtn').classList.toggle('active',fav.includes(a.id));$('#heartBtn').textContent=fav.includes(a.id)?'♥':'♡';$$('.rating-row button').forEach(b=>b.classList.toggle('selected',ratings[a.id]===b.dataset.rating));const owns=a.tools.length===0||a.tools.every(t=>inventory.includes(t));$('#ownedNote').textContent=owns?'✓ Vyzerá to, že potrebné veci už máte doma.':'Tip: chýbajúcu pomôcku môžeš často nahradiť podobnou bezpečnou vecou.';showView('activity')}
function meter(n){return '●'.repeat(Math.max(1,Math.min(4,n)))+'○'.repeat(4-Math.max(1,Math.min(4,n)))}
function applyMode(mode){const f={location:'home',time:20,categories:[],solo:false,noPrep:false,noMess:false,onlyNew:false,atHome:false,siblings:false};let pe=state.parentEnergy,ce=state.childEnergy;if(mode==='quiet'){f.solo=true;f.noPrep=true;f.noMess=true;f.categories=['calm','brain','creative'];pe='zero'}if(mode==='energy'){f.categories=['movement'];f.noPrep=true;ce='hyper'}if(mode==='rain'){f.location='home';f.time=40;f.categories=['creative','pretend','brain','movement']}if(mode==='restaurant'){f.location='restaurant';f.noMess=true;f.noPrep=true;f.time=20;pe='zero'}if(mode==='cook'){f.location='home';f.solo=true;f.noPrep=true;f.time=20;pe='zero'}if(mode==='phone'){f.location='home';f.solo=true;f.noPrep=true;f.noMess=true;f.categories=['calm','brain'];pe='zero'}if(mode==='travel'){f.location='travel';f.noPrep=true;f.noMess=true;f.time=40;pe='zero'}if(mode==='nothing'){f.location='home';f.noPrep=true;f.atHome=true;f.time=20}if(mode==='siblings'){f.siblings=true;f.location='home';f.time=40}showActivity(pick({filters:f,parentEnergy:pe,childEnergy:ce}))}
function renderHome(){const p=profile();$('#activeAvatar').textContent=$('#profileAvatar').textContent=p.avatar;$('#activeName').textContent=p.name;$('#activeAge').textContent=ageText(p.age);$('#dailyName').textContent=p.name.toLowerCase();$('#savedCount').textContent=fav.length;const loved=Object.values(ratings).filter(x=>x==='love').length, played=new Set(history.map(x=>x.id)).size;if(played){$('#insightTitle').textContent=`Máte za sebou ${played} rôznych hier.`;$('#insightText').textContent=loved?`${loved} z nich ste označili ❤️. Pri ďalšom výbere ich preferencie používame.`:'Označ, čo zafungovalo, a výber bude postupne osobnejší.'}renderWeek()}
function renderWeek(){const p=profile(), key=new Date().toISOString().slice(0,10), saved=load(KEYS.week,null);let ids=saved?.profile===p.id&&saved?.key===key?saved.ids:null;if(!ids){const cats=['movement','creative','brain','pretend','outside','calm','sensory'];ids=cats.map((c,i)=>{let pool=db.filter(a=>a.ageMin===p.age&&(c==='outside'?a.locations.includes('outside'):a.category===c));return pool[(new Date().getDate()+i*7)%pool.length]?.id}).filter(Boolean);save(KEYS.week,{profile:p.id,key,ids})}const days=['PO','UT','ST','ŠT','PI','SO','NE'];$('#weekStrip').innerHTML=ids.slice(0,7).map((id,i)=>{const a=db.find(x=>x.id===id);return `<button class="day-card" data-id="${id}"><span class="day">${days[i]}</span><span class="emoji">${a.emoji}</span><b>${esc(a.title)}</b><small>${a.time} min</small></button>`}).join('');$$('.day-card').forEach(b=>b.onclick=()=>showActivity(db.find(a=>a.id===b.dataset.id)))}
function renderResults(){const list=rankActivities().slice(0,24);$('#resultCount').textContent=rankActivities().length;$('#resultGrid').innerHTML=list.length?list.map(tile).join(''):`<div class="empty"><span>🫠</span><b>Na tieto filtre nič nesedí.</b><p>Skús jednu podmienku povoliť.</p></div>`;bindTiles()}
function tile(a){const played=history.some(h=>h.id===a.id);return `<button class="activity-tile" data-id="${a.id}"><div class="tile-visual"><span>${a.emoji}</span></div><div class="tile-body"><span class="eyebrow">${categoryLabel(a.category).toUpperCase()}</span><h3>${esc(a.title)}</h3><p>${esc(a.intro)}</p><div class="tile-meta"><span>⏱ ${a.time} min</span><span>${a.prep===0?'⚡ bez prípravy':`🧑 ${a.prep} min príprava`}</span>${played?'<span>🕘 hrané</span>':'<span>✨ nové</span>'}</div></div></button>`}
function bindTiles(root=document){$$('.activity-tile',root).forEach(b=>b.onclick=()=>showActivity(db.find(a=>a.id===b.dataset.id)))}
function renderKidChoices(){const list=rankActivities({filters:{location:'home',time:25,categories:[],solo:false,noPrep:true,noMess:false,onlyNew:false,atHome:false,siblings:false}});const picks=[];for(const a of list){if(!picks.some(x=>x.category===a.category))picks.push(a);if(picks.length===3)break}$('#kidOptions').innerHTML=picks.map(a=>`<button class="kid-card" data-id="${a.id}"><span>${a.emoji}</span><div><b>${esc(a.title)}</b><small>${a.time} min</small></div></button>`).join('');$$('.kid-card').forEach(b=>b.onclick=()=>showActivity(db.find(a=>a.id===b.dataset.id)))}
function renderSaved(tab='favorites'){const ids=tab==='favorites'?fav:tab==='loved'?Object.keys(ratings).filter(k=>ratings[k]==='love'):[...new Set(history.map(h=>h.id))];const list=ids.map(id=>db.find(a=>a.id===id)).filter(Boolean);$('#savedGrid').innerHTML=list.length?list.map(tile).join(''):`<div class="empty"><span>${tab==='favorites'?'♡':'🌱'}</span><b>Zatiaľ je tu prázdno.</b><p>Keď nájdete dobrú hru, ulož ju alebo ohodnoť.</p></div>`;bindTiles($('#savedGrid'))}
function renderProgress(){const unique=[...new Set(history.map(h=>h.id))].map(id=>db.find(a=>a.id===id)).filter(Boolean), loved=Object.values(ratings).filter(x=>x==='love').length, cats=new Set(unique.map(a=>a.category)).size, outside=unique.filter(a=>a.locations.includes('outside')).length;$('#statsGrid').innerHTML=[[ '🎲',unique.length,'rôznych hier'],['❤️',loved,'milovaných'],['🌈',cats,'typov aktivít'],['🌳',outside,'outdoor nápadov']].map(x=>`<div class="stat-card"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');const ach=[['🌱','Prvý krok','Skúste prvú aktivitu',unique.length>=1],['🎨','Picasso junior','5 tvorivých aktivít',unique.filter(a=>a.category==='creative').length>=5],['⚡','Energia von!','5 pohybových hier',unique.filter(a=>a.category==='movement').length>=5],['🧠','Malý objaviteľ','5 premýšľacích hier',unique.filter(a=>a.category==='brain').length>=5],['🌳','Vonku je najlepšie','5 outdoor aktivít',outside>=5],['🌈','Skúsili sme všeličo','5 rôznych typov hier',cats>=5]];$('#achievementGrid').innerHTML=ach.map(a=>`<div class="achievement ${a[3]?'unlocked':''}"><span>${a[0]}</span><b>${a[1]}</b><small>${a[2]}</small></div>`).join('')}
function renderProfile(){const p=profile();$('#childList').innerHTML=profiles.map(x=>`<button class="child-row ${x.id===p.id?'active':''}" data-id="${x.id}"><span class="avatar">${x.avatar}</span><span><b>${esc(x.name)}</b><small>${ageText(x.age)}</small></span><span>→</span></button>`).join('');$$('.child-row').forEach(b=>b.onclick=()=>{state.activeChild=b.dataset.id;saveAll();renderProfile();renderHome()});$('#profileEditor').innerHTML=`<div class="editor-grid"><label>Meno<input id="editName" value="${esc(p.name)}" maxlength="20"></label><label>Vek<select id="editAge">${[2,3,4,5,6,7,8].map(a=>`<option ${a===p.age?'selected':''}>${a}</option>`).join('')}</select></label><label>Avatar<select id="editAvatar">${['🦊','🐻','🐰','🦁','🐼','🐨','🦄','🚀'].map(a=>`<option ${a===p.avatar?'selected':''}>${a}</option>`).join('')}</select></label><label>Poznámka<input id="editNotes" value="${esc(p.notes||'')}" placeholder="napr. miluje dinosaury"></label></div><h3>Čo ho/ju baví?</h3><div class="interest-grid">${interests.map(([v,l])=>`<label><input type="checkbox" value="${v}" ${p.interests?.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}</div><div style="margin-top:14px;display:flex;gap:8px"><button class="primary-btn" id="saveProfile">Uložiť profil</button>${profiles.length>1?'<button class="ghost-btn" id="deleteProfile">Odstrániť</button>':''}</div>`;$('#saveProfile').onclick=()=>{p.name=$('#editName').value.trim()||'Dieťa';p.age=Number($('#editAge').value);p.avatar=$('#editAvatar').value;p.notes=$('#editNotes').value.trim();p.interests=$$('.interest-grid input:checked').map(x=>x.value);saveAll();renderProfile();renderHome();toast('Profil uložený ✓')};if($('#deleteProfile'))$('#deleteProfile').onclick=()=>{if(confirm('Odstrániť tento profil?')){profiles=profiles.filter(x=>x.id!==p.id);state.activeChild=profiles[0].id;saveAll();renderProfile();renderHome()}};$('#inventoryGrid').innerHTML=inventoryItems.map(([v,l])=>`<label><input type="checkbox" value="${v}" ${inventory.includes(v)?'checked':''}><span>${l}</span></label>`).join('');$$('#inventoryGrid input').forEach(i=>i.onchange=()=>{inventory=$$('#inventoryGrid input:checked').map(x=>x.value);save(KEYS.inventory,inventory)})}
function markPlayed(){if(!current)return;history.unshift({id:current.id,at:Date.now(),child:state.activeChild});history=history.slice(0,500);save(KEYS.history,history);confetti();toast('Hotovo! Milá stopa je uložená 🌟');beep();renderHome()}
function confetti(){if(!state.motion)return;const box=$('#confetti'),colors=['#ff765f','#ffd15c','#8fd8b7','#9cb8ff','#c9a6ff'];for(let i=0;i<24;i++){const e=document.createElement('i');e.style.left=Math.random()*100+'%';e.style.background=colors[i%colors.length];e.style.animationDelay=Math.random()*.25+'s';box.appendChild(e);setTimeout(()=>e.remove(),1500)}}
function toggleFav(){if(!current)return;fav=fav.includes(current.id)?fav.filter(x=>x!==current.id):[current.id,...fav];save(KEYS.fav,fav);$('#heartBtn').classList.toggle('active',fav.includes(current.id));$('#heartBtn').textContent=fav.includes(current.id)?'♥':'♡';$('#savedCount').textContent=fav.length;toast(fav.includes(current.id)?'Uložené do obľúbených ♡':'Odstránené z obľúbených')}
function setRating(r){if(!current)return;ratings[current.id]=r;save(KEYS.ratings,ratings);$$('.rating-row button').forEach(b=>b.classList.toggle('selected',b.dataset.rating===r));if(!history.some(h=>h.id===current.id))markPlayed();toast(r==='love'?'Zapamätáme si, že toto funguje ❤️':r==='no'?'OK, podobné hry budeme tlačiť nižšie.':'Super, berieme na vedomie 🙂')}
function renderSwitch(){const p=profile();$('#switchChildList').innerHTML=profiles.map(x=>`<button class="child-row ${x.id===p.id?'active':''}" data-id="${x.id}"><span class="avatar">${x.avatar}</span><span><b>${esc(x.name)}</b><small>${ageText(x.age)}</small></span></button>`).join('');$$('#switchChildList .child-row').forEach(b=>b.onclick=()=>{state.activeChild=b.dataset.id;saveAll();$('#switchChildDialog').close();renderHome()})}
function addChild(){const id='c'+Date.now();profiles.push({id,name:'Nové dieťa',age:3,avatar:'🐰',interests:[],notes:''});state.activeChild=id;saveAll();renderProfile()}
function syncFilters(){const f=state.filters;$$('#locationChips button').forEach(b=>b.classList.toggle('active',b.dataset.value===f.location));$$('#timeChips button').forEach(b=>b.classList.toggle('active',Number(b.dataset.value)===Number(f.time)));$$('#categoryChips button').forEach(b=>b.classList.toggle('active',f.categories.includes(b.dataset.value)));$('#fSolo').checked=f.solo;$('#fNoPrep').checked=f.noPrep;$('#fNoMess').checked=f.noMess;$('#fOnlyNew').checked=f.onlyNew;$('#fAtHome').checked=f.atHome;$('#fSiblings').checked=f.siblings}
function parseVoice(text){text=text.toLowerCase();if(/reštaur|čak/.test(text))state.filters.location='restaurant';else if(/auto|cest|vlak|lietad/.test(text))state.filters.location='travel';else if(/vonku|ihrisk/.test(text))state.filters.location='outside';else state.filters.location='home';const m=text.match(/(5|10|15|20|30|40)\s*(min|minút)/);if(m)state.filters.time=Number(m[1])<=10?5:Number(m[1])<=20?20:40;if(/bez pomôc|nič/.test(text)){state.filters.noPrep=true;state.filters.atHome=true}if(/tich|pokoj/.test(text))state.filters.categories=['calm','brain'];if(/pohyb|energi|hyper/.test(text))state.filters.categories=['movement'];if(/samo|samostat/.test(text))state.filters.solo=true;syncFilters();renderResults();showView('discover')}
function setupVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Hlasový vstup tento prehliadač nepodporuje.');return}const r=new SR();r.lang='sk-SK';r.interimResults=false;r.onstart=()=>{$('#voiceOrb').classList.add('listening');$('#voiceCopy').textContent='Počúvam…'};r.onresult=e=>{const t=e.results[0][0].transcript;$('#voiceCopy').textContent=`„${t}“`;parseVoice(t);setTimeout(()=>$('#voiceDialog').close(),700)};r.onerror=()=>{$('#voiceCopy').textContent='Nepodarilo sa rozpoznať hlas. Skús to ešte raz.'};r.onend=()=>$('#voiceOrb').classList.remove('listening');r.start()}
function install(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.finally(()=>deferredPrompt=null);return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installCopy').innerHTML=ios?'<p>V Safari ťukni na <b>Zdieľať</b> → <b>Pridať na plochu</b> → potvrď.</p>':'<p>V menu prehliadača vyber <b>Nainštalovať aplikáciu</b> alebo <b>Pridať na plochu</b>.</p>';$('#installDialog').showModal()}
function bind(){
 $$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-back]').forEach(b=>b.onclick=()=>showView(b.dataset.back||'home'));$('#profileQuick').onclick=()=>showView('profile');
 $$('#childEnergy button').forEach(b=>b.onclick=()=>{state.childEnergy=b.dataset.value;$$('#childEnergy button').forEach(x=>x.classList.toggle('active',x===b));save(KEYS.state,state)});$$('#parentEnergy button').forEach(b=>b.onclick=()=>{state.parentEnergy=b.dataset.value;$$('#parentEnergy button').forEach(x=>x.classList.toggle('active',x===b));save(KEYS.state,state)});
 $('#rescueBtn').onclick=()=>showActivity(pick());$('#openFineTune').onclick=()=>$('#fineTuneDialog').showModal();$('#fineTuneGo').onclick=()=>{state.filters.location=$('#quickLocation').value;state.filters.time=Number($('#quickTime').value);const m=$('#quickMess').value,s=$('#quickSolo').value;state.filters.noMess=m==='none';state.filters.solo=s==='solo';save(KEYS.state,state);showActivity(pick())};$$('#situationGrid .situation').forEach(b=>b.onclick=()=>applyMode(b.dataset.mode));
 $('#dailyBtn').onclick=()=>showActivity(pick({filters:{location:'home',time:25,categories:[],solo:false,noPrep:false,noMess:false,onlyNew:true,atHome:false,siblings:false}}));$('#regenWeek').onclick=()=>{localStorage.removeItem(KEYS.week);renderWeek();toast('Týždeň vymenený ✨')};
 $$('#locationChips button').forEach(b=>b.onclick=()=>{state.filters.location=b.dataset.value;syncFilters();renderResults()});$$('#timeChips button').forEach(b=>b.onclick=()=>{state.filters.time=Number(b.dataset.value);syncFilters();renderResults()});$$('#categoryChips button').forEach(b=>b.onclick=()=>{const v=b.dataset.value;state.filters.categories=state.filters.categories.includes(v)?state.filters.categories.filter(x=>x!==v):[...state.filters.categories,v];syncFilters();renderResults()});
 [['fSolo','solo'],['fNoPrep','noPrep'],['fNoMess','noMess'],['fOnlyNew','onlyNew'],['fAtHome','atHome'],['fSiblings','siblings']].forEach(([id,k])=>$('#'+id).onchange=e=>{state.filters[k]=e.target.checked;renderResults()});$('#resetFilters').onclick=()=>{state.filters=clone(defaults.filters);syncFilters();renderResults()};$('#searchBtn').onclick=renderResults;$('#randomFromResults').onclick=()=>showActivity(rankActivities()[Math.floor(Math.random()*Math.min(10,rankActivities().length))]);
 $('#heartBtn').onclick=toggleFav;$('#playedBtn').onclick=markPlayed;$('#anotherBtn').onclick=()=>showActivity(pick());$$('.rating-row button').forEach(b=>b.onclick=()=>setRating(b.dataset.rating));$('#easierBtn').onclick=()=>toast(current?.easier||'');$('#harderBtn').onclick=()=>toast(current?.harder||'');
 $$('#savedTabs button').forEach(b=>b.onclick=()=>{$$('#savedTabs button').forEach(x=>x.classList.toggle('active',x===b));renderSaved(b.dataset.tab)});
 $('#switchChildBtn').onclick=()=>{renderSwitch();$('#switchChildDialog').showModal()};$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('[data-open-profile]').forEach(b=>b.onclick=()=>{b.closest('dialog').close();showView('profile')});$('#addChildBtn').onclick=addChild;
 $('#voiceBtn').onclick=()=>$('#voiceDialog').showModal();$('#startVoice').onclick=setupVoice;$('#shakeBtn').onclick=()=>showActivity(rankActivities()[Math.floor(Math.random()*Math.min(15,rankActivities().length))]);
 $('#motionToggle').checked=state.motion;$('#soundToggle').checked=state.sound;$('#motionToggle').onchange=e=>{state.motion=e.target.checked;document.body.classList.toggle('no-motion',!state.motion);save(KEYS.state,state)};$('#soundToggle').onchange=e=>{state.sound=e.target.checked;save(KEYS.state,state)};$('#installBtn').onclick=install;$('#clearBtn').onclick=()=>{if(confirm('Naozaj vymazať všetky lokálne údaje tejto verzie?')){Object.values(KEYS).forEach(k=>localStorage.removeItem(k));location.reload()}};
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});window.addEventListener('devicemotion',e=>{const a=e.accelerationIncludingGravity;if(!a)return;const force=Math.abs(a.x||0)+Math.abs(a.y||0)+Math.abs(a.z||0);if(force>32&&Date.now()-lastShake>1800&&$('#kidView')&&!$('#kidView').hidden){lastShake=Date.now();renderKidChoices();toast('Vyžrebované! 🎲')}})
}
function init(){bind();syncFilters();document.body.classList.toggle('no-motion',!state.motion);renderHome();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
init();
})();
